from app.schemas.auth import (
    Token,
    TokenData,
    LoginRequest,
    UserCreate,
    UserUpdate,
    UserResponse,
    PasswordChangeRequest,
)
from app.schemas.room import (
    RoomBase,
    RoomCreate,
    RoomUpdate,
    RoomDetailResponse,
    RoomChartSummary,
    BedBase,
    BedCreate,
    BedResponse,
)
from app.schemas.package import (
    PackageBase,
    PackageCreate,
    PackageUpdate,
    PackageResponse,
)
from app.schemas.enquiry import (
    EnquiryBase,
    EnquiryCreate,
    EnquiryUpdate,
    EnquiryResponse,
)
from app.schemas.guest import (
    GuestBase,
    GuestCreate,
    GuestUpdate,
    GuestResponse,
)
from app.schemas.admission import (
    AdmissionCreate,
    AdmissionUpdate,
    AdmissionCheckout,
    AdmissionResponse,
)
from app.schemas.booking import (
    BookingBase,
    BookingCreate,
    BookingUpdate,
    BookingResponse,
)
from app.schemas.attendance import (
    AttendanceRecord,
    BulkAttendanceCreate,
    AttendanceResponse,
    AttendanceSummary,
)
from app.schemas.finance import (
    FeeReceiptCreate,
    FeeReceiptResponse,
    AccountTransactionCreate,
    AccountTransactionResponse,
    AccountSummary,
)
from app.schemas.dashboard import (
    FloorOccupancy,
    DashboardMetrics,
)
from app.schemas.settings import (
    MaintenanceRecordBase,
    MaintenanceRecordCreate,
    MaintenanceRecordUpdate,
    MaintenanceRecordResponse,
    HostelSettingBase,
    HostelSettingCreate,
    HostelSettingResponse,
)

__all__ = [
    "Token",
    "TokenData",
    "LoginRequest",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "PasswordChangeRequest",
    "RoomBase",
    "RoomCreate",
    "RoomUpdate",
    "RoomDetailResponse",
    "RoomChartSummary",
    "BedBase",
    "BedCreate",
    "BedResponse",
    "PackageBase",
    "PackageCreate",
    "PackageUpdate",
    "PackageResponse",
    "EnquiryBase",
    "EnquiryCreate",
    "EnquiryUpdate",
    "EnquiryResponse",
    "GuestBase",
    "GuestCreate",
    "GuestUpdate",
    "GuestResponse",
    "AdmissionCreate",
    "AdmissionUpdate",
    "AdmissionCheckout",
    "AdmissionResponse",
    "BookingBase",
    "BookingCreate",
    "BookingUpdate",
    "BookingResponse",
    "AttendanceRecord",
    "BulkAttendanceCreate",
    "AttendanceResponse",
    "AttendanceSummary",
    "FeeReceiptCreate",
    "FeeReceiptResponse",
    "AccountTransactionCreate",
    "AccountTransactionResponse",
    "AccountSummary",
    "FloorOccupancy",
    "DashboardMetrics",
    "MaintenanceRecordBase",
    "MaintenanceRecordCreate",
    "MaintenanceRecordUpdate",
    "MaintenanceRecordResponse",
    "HostelSettingBase",
    "HostelSettingCreate",
    "HostelSettingResponse",
]
